version: '3.8'

services:
  app:
    build: .
    ports:
      - "3030:3030"
    command: bash -c "uvicorn --host 0.0.0.0 --port 3030 app.main:app --reload"
    depends_on:
      - app_db

  app_db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: